language: node_js
node_js:
- '6'
before_script:
- npm install -g webpack
- npm install -g codecov
before_deploy:
- npm run deploy
deploy:
  provider: heroku
  app: jalgo-arena-ui-pg
  api_key:
    secure: "9855590b-8959-4807-85b7-183375c6a947"
